---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package and add php support on apchae
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
